import type { Locale } from './routing'

export const batchTwo: Record<Locale, {
  done: string; doneBody: string; previous: string; next: string; group: string
  clientRating: string; retention: string; countries: string
  privacy: string; terms: string; cookies: string; preferences: string
  analytics: string; marketing: string; essential: string; save: string; close: string
}> = {
  en: { done: 'Done!', doneBody: 'The top 3% of tech talent are hired and can start client delivery.', previous: 'Previous testimonials', next: 'Next testimonials', group: 'Testimonial group', clientRating: 'Client Rating', retention: 'Client Retention', countries: 'Countries Served', privacy: 'Privacy Policy', terms: 'Terms & Conditions', cookies: 'Cookie Policy', preferences: 'Cookie Preferences', analytics: 'Analytics', marketing: 'Marketing', essential: 'Essential cookies are always enabled to remember your settings and keep the website working.', save: 'Save preferences', close: 'Close' },
  ar: { done: 'تم!', doneBody: 'تم توظيف أفضل ٣٪ من المواهب التقنية وهم جاهزون لبدء العمل مع العملاء.', previous: 'آراء العملاء السابقة', next: 'آراء العملاء التالية', group: 'مجموعة آراء العملاء', clientRating: 'تقييم العملاء', retention: 'الاحتفاظ بالعملاء', countries: 'دولة نخدمها', privacy: 'سياسة الخصوصية', terms: 'الشروط والأحكام', cookies: 'سياسة ملفات الارتباط', preferences: 'تفضيلات ملفات الارتباط', analytics: 'التحليلات', marketing: 'التسويق', essential: 'ملفات الارتباط الأساسية مفعّلة دائمًا لحفظ إعداداتك وضمان عمل الموقع.', save: 'حفظ التفضيلات', close: 'إغلاق' },
  de: { done: 'Geschafft!', doneBody: 'Die besten 3 % der Tech-Talente sind eingestellt und können mit der Kundenarbeit beginnen.', previous: 'Vorherige Kundenstimmen', next: 'Nächste Kundenstimmen', group: 'Gruppe von Kundenstimmen', clientRating: 'Kundenbewertung', retention: 'Kundenbindung', countries: 'Betreute Länder', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', cookies: 'Cookie-Richtlinie', preferences: 'Cookie-Einstellungen', analytics: 'Analyse', marketing: 'Marketing', essential: 'Notwendige Cookies sind immer aktiv, um Ihre Einstellungen zu speichern und die Website zu betreiben.', save: 'Einstellungen speichern', close: 'Schließen' },
  fr: { done: 'Terminé !', doneBody: 'Les meilleurs 3 % des talents tech sont recrutés et prêts à travailler pour les clients.', previous: 'Témoignages précédents', next: 'Témoignages suivants', group: 'Groupe de témoignages', clientRating: 'Note des clients', retention: 'Fidélisation client', countries: 'Pays desservis', privacy: 'Confidentialité', terms: 'Conditions générales', cookies: 'Politique de cookies', preferences: 'Préférences de cookies', analytics: 'Analyse', marketing: 'Marketing', essential: 'Les cookies essentiels restent actifs pour mémoriser vos réglages et assurer le fonctionnement du site.', save: 'Enregistrer les préférences', close: 'Fermer' },
  es: { done: '¡Listo!', doneBody: 'El 3 % del mejor talento tecnológico está contratado y listo para trabajar con los clientes.', previous: 'Testimonios anteriores', next: 'Testimonios siguientes', group: 'Grupo de testimonios', clientRating: 'Valoración de clientes', retention: 'Retención de clientes', countries: 'Países atendidos', privacy: 'Privacidad', terms: 'Términos y condiciones', cookies: 'Política de cookies', preferences: 'Preferencias de cookies', analytics: 'Analítica', marketing: 'Marketing', essential: 'Las cookies esenciales están siempre activas para recordar tus ajustes y mantener el sitio en funcionamiento.', save: 'Guardar preferencias', close: 'Cerrar' },
}
