import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_hero_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_hero_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_hiring_models_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_hiring_models_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_talent_showcase_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_talent_showcase_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_cards_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_cards_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_card_grid_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_faq_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_faq_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_posts_teaser_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_posts_teaser_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_pages_blocks_cta_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_pages_blocks_cta_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_hero_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_hiring_models_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_hiring_models_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_talent_showcase_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_talent_showcase_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_card_grid_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_faq_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_faq_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_posts_teaser_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_posts_teaser_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_hero_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_hero_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_hiring_models_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_hiring_models_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_talent_showcase_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_talent_showcase_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_card_grid_cards_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_card_grid_cards_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_card_grid_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_card_grid_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_faq_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_faq_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_posts_teaser_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_posts_teaser_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_posts_blocks_cta_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_posts_blocks_cta_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_hero_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_hero_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_hiring_models_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_hiring_models_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_talent_showcase_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_talent_showcase_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_card_grid_cards_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_card_grid_cards_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_card_grid_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_card_grid_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_faq_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_faq_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_posts_teaser_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_posts_teaser_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__posts_v_blocks_cta_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__posts_v_blocks_cta_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_hero_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_hero_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_hiring_models_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_hiring_models_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_talent_showcase_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_talent_showcase_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_card_grid_cards_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_card_grid_cards_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_card_grid_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_card_grid_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_faq_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_faq_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_posts_teaser_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_posts_teaser_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_services_blocks_cta_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_services_blocks_cta_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_hero_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_hero_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_hiring_models_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_hiring_models_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_talent_showcase_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_talent_showcase_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_card_grid_cards_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_card_grid_cards_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_card_grid_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_card_grid_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_faq_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_faq_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_posts_teaser_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_posts_teaser_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__services_v_blocks_cta_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__services_v_blocks_cta_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_header_items_children_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_header_items_children_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_header_items_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_header_items_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_header_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_header_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_header_announcement_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_header_announcement_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__header_v_version_items_children_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__header_v_version_items_children_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__header_v_version_items_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__header_v_version_items_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__header_v_version_ctas_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__header_v_version_ctas_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__header_v_version_announcement_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__header_v_version_announcement_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_footer_columns_links_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_footer_columns_links_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum_footer_legal_links_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum_footer_legal_links_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__footer_v_version_columns_links_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__footer_v_version_columns_links_link_route" ADD VALUE '/meet-fika-ai';
  ALTER TYPE "public"."enum__footer_v_version_legal_links_link_route" ADD VALUE '/about';
  ALTER TYPE "public"."enum__footer_v_version_legal_links_link_route" ADD VALUE '/meet-fika-ai';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_hero_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_hero_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_hero_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_hero_ctas_link_route";
  ALTER TABLE "pages_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_hiring_models_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_hiring_models_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_hiring_models_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_hiring_models_ctas_link_route";
  ALTER TABLE "pages_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_talent_showcase_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_talent_showcase_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_talent_showcase_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_talent_showcase_ctas_link_route";
  ALTER TABLE "pages_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_card_grid_cards_link_route";
  CREATE TYPE "public"."enum_pages_blocks_card_grid_cards_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_card_grid_cards_link_route" USING "link_route"::"public"."enum_pages_blocks_card_grid_cards_link_route";
  ALTER TABLE "pages_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_card_grid_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_card_grid_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_card_grid_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_card_grid_ctas_link_route";
  ALTER TABLE "pages_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_faq_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_faq_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_faq_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_faq_ctas_link_route";
  ALTER TABLE "pages_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_posts_teaser_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_posts_teaser_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_posts_teaser_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_posts_teaser_ctas_link_route";
  ALTER TABLE "pages_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_cta_ctas_link_route";
  CREATE TYPE "public"."enum_pages_blocks_cta_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "pages_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_pages_blocks_cta_ctas_link_route" USING "link_route"::"public"."enum_pages_blocks_cta_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_hero_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_hero_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_hiring_models_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_hiring_models_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_hiring_models_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_hiring_models_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_talent_showcase_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_talent_showcase_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_talent_showcase_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_talent_showcase_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_card_grid_cards_link_route" USING "link_route"::"public"."enum__pages_v_blocks_card_grid_cards_link_route";
  ALTER TABLE "_pages_v_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_card_grid_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_card_grid_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_card_grid_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_card_grid_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_faq_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_faq_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_faq_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_faq_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_posts_teaser_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_posts_teaser_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_posts_teaser_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_posts_teaser_ctas_link_route";
  ALTER TABLE "_pages_v_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_ctas_link_route";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_pages_v_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__pages_v_blocks_cta_ctas_link_route" USING "link_route"::"public"."enum__pages_v_blocks_cta_ctas_link_route";
  ALTER TABLE "posts_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_hero_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_hero_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_hero_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_hero_ctas_link_route";
  ALTER TABLE "posts_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_hiring_models_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_hiring_models_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_hiring_models_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_hiring_models_ctas_link_route";
  ALTER TABLE "posts_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_talent_showcase_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_talent_showcase_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_talent_showcase_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_talent_showcase_ctas_link_route";
  ALTER TABLE "posts_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_card_grid_cards_link_route";
  CREATE TYPE "public"."enum_posts_blocks_card_grid_cards_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_card_grid_cards_link_route" USING "link_route"::"public"."enum_posts_blocks_card_grid_cards_link_route";
  ALTER TABLE "posts_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_card_grid_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_card_grid_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_card_grid_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_card_grid_ctas_link_route";
  ALTER TABLE "posts_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_faq_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_faq_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_faq_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_faq_ctas_link_route";
  ALTER TABLE "posts_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_posts_teaser_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_posts_teaser_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_posts_teaser_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_posts_teaser_ctas_link_route";
  ALTER TABLE "posts_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_blocks_cta_ctas_link_route";
  CREATE TYPE "public"."enum_posts_blocks_cta_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "posts_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_posts_blocks_cta_ctas_link_route" USING "link_route"::"public"."enum_posts_blocks_cta_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_hero_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_hero_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_hero_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_hero_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_hiring_models_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_hiring_models_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_hiring_models_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_hiring_models_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_talent_showcase_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_talent_showcase_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_talent_showcase_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_talent_showcase_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_card_grid_cards_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_card_grid_cards_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_card_grid_cards_link_route" USING "link_route"::"public"."enum__posts_v_blocks_card_grid_cards_link_route";
  ALTER TABLE "_posts_v_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_card_grid_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_card_grid_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_card_grid_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_card_grid_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_faq_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_faq_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_faq_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_faq_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_posts_teaser_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_posts_teaser_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_posts_teaser_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_posts_teaser_ctas_link_route";
  ALTER TABLE "_posts_v_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_blocks_cta_ctas_link_route";
  CREATE TYPE "public"."enum__posts_v_blocks_cta_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_posts_v_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__posts_v_blocks_cta_ctas_link_route" USING "link_route"::"public"."enum__posts_v_blocks_cta_ctas_link_route";
  ALTER TABLE "services_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_hero_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_hero_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_hero_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_hero_ctas_link_route";
  ALTER TABLE "services_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_hiring_models_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_hiring_models_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_hiring_models_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_hiring_models_ctas_link_route";
  ALTER TABLE "services_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_talent_showcase_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_talent_showcase_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_talent_showcase_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_talent_showcase_ctas_link_route";
  ALTER TABLE "services_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_card_grid_cards_link_route";
  CREATE TYPE "public"."enum_services_blocks_card_grid_cards_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_card_grid_cards_link_route" USING "link_route"::"public"."enum_services_blocks_card_grid_cards_link_route";
  ALTER TABLE "services_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_card_grid_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_card_grid_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_card_grid_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_card_grid_ctas_link_route";
  ALTER TABLE "services_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_faq_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_faq_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_faq_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_faq_ctas_link_route";
  ALTER TABLE "services_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_posts_teaser_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_posts_teaser_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_posts_teaser_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_posts_teaser_ctas_link_route";
  ALTER TABLE "services_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_services_blocks_cta_ctas_link_route";
  CREATE TYPE "public"."enum_services_blocks_cta_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "services_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_services_blocks_cta_ctas_link_route" USING "link_route"::"public"."enum_services_blocks_cta_ctas_link_route";
  ALTER TABLE "_services_v_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_hero_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_hero_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_hero_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_hero_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_hero_ctas_link_route";
  ALTER TABLE "_services_v_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_hiring_models_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_hiring_models_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_hiring_models_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_hiring_models_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_hiring_models_ctas_link_route";
  ALTER TABLE "_services_v_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_talent_showcase_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_talent_showcase_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_talent_showcase_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_talent_showcase_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_talent_showcase_ctas_link_route";
  ALTER TABLE "_services_v_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_card_grid_cards_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_card_grid_cards_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_card_grid_cards" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_card_grid_cards_link_route" USING "link_route"::"public"."enum__services_v_blocks_card_grid_cards_link_route";
  ALTER TABLE "_services_v_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_card_grid_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_card_grid_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_card_grid_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_card_grid_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_card_grid_ctas_link_route";
  ALTER TABLE "_services_v_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_faq_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_faq_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_faq_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_faq_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_faq_ctas_link_route";
  ALTER TABLE "_services_v_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_posts_teaser_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_posts_teaser_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_posts_teaser_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_posts_teaser_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_posts_teaser_ctas_link_route";
  ALTER TABLE "_services_v_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__services_v_blocks_cta_ctas_link_route";
  CREATE TYPE "public"."enum__services_v_blocks_cta_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_services_v_blocks_cta_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__services_v_blocks_cta_ctas_link_route" USING "link_route"::"public"."enum__services_v_blocks_cta_ctas_link_route";
  ALTER TABLE "header_items_children" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_header_items_children_link_route";
  CREATE TYPE "public"."enum_header_items_children_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "header_items_children" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_header_items_children_link_route" USING "link_route"::"public"."enum_header_items_children_link_route";
  ALTER TABLE "header_items" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_header_items_link_route";
  CREATE TYPE "public"."enum_header_items_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "header_items" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_header_items_link_route" USING "link_route"::"public"."enum_header_items_link_route";
  ALTER TABLE "header_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_header_ctas_link_route";
  CREATE TYPE "public"."enum_header_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "header_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_header_ctas_link_route" USING "link_route"::"public"."enum_header_ctas_link_route";
  ALTER TABLE "header" ALTER COLUMN "announcement_link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_header_announcement_link_route";
  CREATE TYPE "public"."enum_header_announcement_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "header" ALTER COLUMN "announcement_link_route" SET DATA TYPE "public"."enum_header_announcement_link_route" USING "announcement_link_route"::"public"."enum_header_announcement_link_route";
  ALTER TABLE "_header_v_version_items_children" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__header_v_version_items_children_link_route";
  CREATE TYPE "public"."enum__header_v_version_items_children_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_header_v_version_items_children" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__header_v_version_items_children_link_route" USING "link_route"::"public"."enum__header_v_version_items_children_link_route";
  ALTER TABLE "_header_v_version_items" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__header_v_version_items_link_route";
  CREATE TYPE "public"."enum__header_v_version_items_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_header_v_version_items" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__header_v_version_items_link_route" USING "link_route"::"public"."enum__header_v_version_items_link_route";
  ALTER TABLE "_header_v_version_ctas" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__header_v_version_ctas_link_route";
  CREATE TYPE "public"."enum__header_v_version_ctas_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_header_v_version_ctas" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__header_v_version_ctas_link_route" USING "link_route"::"public"."enum__header_v_version_ctas_link_route";
  ALTER TABLE "_header_v" ALTER COLUMN "version_announcement_link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__header_v_version_announcement_link_route";
  CREATE TYPE "public"."enum__header_v_version_announcement_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_header_v" ALTER COLUMN "version_announcement_link_route" SET DATA TYPE "public"."enum__header_v_version_announcement_link_route" USING "version_announcement_link_route"::"public"."enum__header_v_version_announcement_link_route";
  ALTER TABLE "footer_columns_links" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_footer_columns_links_link_route";
  CREATE TYPE "public"."enum_footer_columns_links_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "footer_columns_links" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_footer_columns_links_link_route" USING "link_route"::"public"."enum_footer_columns_links_link_route";
  ALTER TABLE "footer_legal_links" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum_footer_legal_links_link_route";
  CREATE TYPE "public"."enum_footer_legal_links_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "footer_legal_links" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum_footer_legal_links_link_route" USING "link_route"::"public"."enum_footer_legal_links_link_route";
  ALTER TABLE "_footer_v_version_columns_links" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__footer_v_version_columns_links_link_route";
  CREATE TYPE "public"."enum__footer_v_version_columns_links_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_footer_v_version_columns_links" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__footer_v_version_columns_links_link_route" USING "link_route"::"public"."enum__footer_v_version_columns_links_link_route";
  ALTER TABLE "_footer_v_version_legal_links" ALTER COLUMN "link_route" SET DATA TYPE text;
  DROP TYPE "public"."enum__footer_v_version_legal_links_link_route";
  CREATE TYPE "public"."enum__footer_v_version_legal_links_link_route" AS ENUM('/', '/blog', '/services', '/careers', '/contact', '/meeting');
  ALTER TABLE "_footer_v_version_legal_links" ALTER COLUMN "link_route" SET DATA TYPE "public"."enum__footer_v_version_legal_links_link_route" USING "link_route"::"public"."enum__footer_v_version_legal_links_link_route";`)
}
