import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_hero_mosaic_corner" AS ENUM('tl', 'tr', 'bl', 'br');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_mosaic_corner" AS ENUM('tl', 'tr', 'bl', 'br');
  CREATE TYPE "public"."enum_posts_blocks_hero_mosaic_corner" AS ENUM('tl', 'tr', 'bl', 'br');
  CREATE TYPE "public"."enum__posts_v_blocks_hero_mosaic_corner" AS ENUM('tl', 'tr', 'bl', 'br');
  CREATE TYPE "public"."enum_services_blocks_hero_mosaic_corner" AS ENUM('tl', 'tr', 'bl', 'br');
  CREATE TYPE "public"."enum__services_v_blocks_hero_mosaic_corner" AS ENUM('tl', 'tr', 'bl', 'br');
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "pages_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "pages_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum_pages_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum_pages_blocks_hero_mosaic_tone" AS ENUM('green', 'emerald', 'indigo', 'teal');
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum_pages_blocks_hero_mosaic_tone";
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum_pages_blocks_hero_mosaic_tone" USING "tone"::"public"."enum_pages_blocks_hero_mosaic_tone";
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "_pages_v_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "_pages_v_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum__pages_v_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_mosaic_tone" AS ENUM('green', 'emerald', 'indigo', 'teal');
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum__pages_v_blocks_hero_mosaic_tone";
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum__pages_v_blocks_hero_mosaic_tone" USING "tone"::"public"."enum__pages_v_blocks_hero_mosaic_tone";
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "posts_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "posts_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum_posts_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum_posts_blocks_hero_mosaic_tone" AS ENUM('green', 'emerald', 'indigo', 'teal');
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum_posts_blocks_hero_mosaic_tone";
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum_posts_blocks_hero_mosaic_tone" USING "tone"::"public"."enum_posts_blocks_hero_mosaic_tone";
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "_posts_v_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "_posts_v_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum__posts_v_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum__posts_v_blocks_hero_mosaic_tone" AS ENUM('green', 'emerald', 'indigo', 'teal');
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum__posts_v_blocks_hero_mosaic_tone";
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum__posts_v_blocks_hero_mosaic_tone" USING "tone"::"public"."enum__posts_v_blocks_hero_mosaic_tone";
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "services_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "services_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum_services_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum_services_blocks_hero_mosaic_tone" AS ENUM('green', 'emerald', 'indigo', 'teal');
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum_services_blocks_hero_mosaic_tone";
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum_services_blocks_hero_mosaic_tone" USING "tone"::"public"."enum_services_blocks_hero_mosaic_tone";
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "_services_v_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "_services_v_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum__services_v_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum__services_v_blocks_hero_mosaic_tone" AS ENUM('green', 'emerald', 'indigo', 'teal');
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum__services_v_blocks_hero_mosaic_tone";
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum__services_v_blocks_hero_mosaic_tone" USING "tone"::"public"."enum__services_v_blocks_hero_mosaic_tone";
  ALTER TABLE "pages_blocks_hero_mosaic" ADD COLUMN "corner" "enum_pages_blocks_hero_mosaic_corner" DEFAULT 'tl';
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ADD COLUMN "corner" "enum__pages_v_blocks_hero_mosaic_corner" DEFAULT 'tl';
  ALTER TABLE "posts_blocks_hero_mosaic" ADD COLUMN "corner" "enum_posts_blocks_hero_mosaic_corner" DEFAULT 'tl';
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ADD COLUMN "corner" "enum__posts_v_blocks_hero_mosaic_corner" DEFAULT 'tl';
  ALTER TABLE "services_blocks_hero_mosaic" ADD COLUMN "corner" "enum_services_blocks_hero_mosaic_corner" DEFAULT 'tl';
  ALTER TABLE "_services_v_blocks_hero_mosaic" ADD COLUMN "corner" "enum__services_v_blocks_hero_mosaic_corner" DEFAULT 'tl';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "pages_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "pages_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum_pages_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum_pages_blocks_hero_mosaic_tone" AS ENUM('brand', 'emerald', 'indigo', 'ink');
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum_pages_blocks_hero_mosaic_tone";
  ALTER TABLE "pages_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum_pages_blocks_hero_mosaic_tone" USING "tone"::"public"."enum_pages_blocks_hero_mosaic_tone";
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "_pages_v_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "_pages_v_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum__pages_v_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_mosaic_tone" AS ENUM('brand', 'emerald', 'indigo', 'ink');
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum__pages_v_blocks_hero_mosaic_tone";
  ALTER TABLE "_pages_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum__pages_v_blocks_hero_mosaic_tone" USING "tone"::"public"."enum__pages_v_blocks_hero_mosaic_tone";
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "posts_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "posts_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum_posts_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum_posts_blocks_hero_mosaic_tone" AS ENUM('brand', 'emerald', 'indigo', 'ink');
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum_posts_blocks_hero_mosaic_tone";
  ALTER TABLE "posts_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum_posts_blocks_hero_mosaic_tone" USING "tone"::"public"."enum_posts_blocks_hero_mosaic_tone";
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "_posts_v_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "_posts_v_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum__posts_v_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum__posts_v_blocks_hero_mosaic_tone" AS ENUM('brand', 'emerald', 'indigo', 'ink');
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum__posts_v_blocks_hero_mosaic_tone";
  ALTER TABLE "_posts_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum__posts_v_blocks_hero_mosaic_tone" USING "tone"::"public"."enum__posts_v_blocks_hero_mosaic_tone";
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "services_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "services_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum_services_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum_services_blocks_hero_mosaic_tone" AS ENUM('brand', 'emerald', 'indigo', 'ink');
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum_services_blocks_hero_mosaic_tone";
  ALTER TABLE "services_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum_services_blocks_hero_mosaic_tone" USING "tone"::"public"."enum_services_blocks_hero_mosaic_tone";
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE text;
  UPDATE "_services_v_blocks_hero_mosaic" SET "tone" = 'green' WHERE "tone" = 'brand';
  UPDATE "_services_v_blocks_hero_mosaic" SET "tone" = 'teal' WHERE "tone" = 'ink';
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" DROP DEFAULT;
  DROP TYPE "public"."enum__services_v_blocks_hero_mosaic_tone";
  CREATE TYPE "public"."enum__services_v_blocks_hero_mosaic_tone" AS ENUM('brand', 'emerald', 'indigo', 'ink');
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DEFAULT 'green'::"public"."enum__services_v_blocks_hero_mosaic_tone";
  ALTER TABLE "_services_v_blocks_hero_mosaic" ALTER COLUMN "tone" SET DATA TYPE "public"."enum__services_v_blocks_hero_mosaic_tone" USING "tone"::"public"."enum__services_v_blocks_hero_mosaic_tone";
  ALTER TABLE "pages_blocks_hero_mosaic" DROP COLUMN "corner";
  ALTER TABLE "_pages_v_blocks_hero_mosaic" DROP COLUMN "corner";
  ALTER TABLE "posts_blocks_hero_mosaic" DROP COLUMN "corner";
  ALTER TABLE "_posts_v_blocks_hero_mosaic" DROP COLUMN "corner";
  ALTER TABLE "services_blocks_hero_mosaic" DROP COLUMN "corner";
  ALTER TABLE "_services_v_blocks_hero_mosaic" DROP COLUMN "corner";
  DROP TYPE "public"."enum_pages_blocks_hero_mosaic_corner";
  DROP TYPE "public"."enum__pages_v_blocks_hero_mosaic_corner";
  DROP TYPE "public"."enum_posts_blocks_hero_mosaic_corner";
  DROP TYPE "public"."enum__posts_v_blocks_hero_mosaic_corner";
  DROP TYPE "public"."enum_services_blocks_hero_mosaic_corner";
  DROP TYPE "public"."enum__services_v_blocks_hero_mosaic_corner";`)
}
